### ISSUE TITLE
README missing package information

### ISSUE THREAD

**Issue by wtrocki** [redhat-developer/app-services-sdk-java#105]
Table in readme.md file is missing references to maven central. (Values there are `TBA`)
Packages are available in individual readmes:

https://github.com/redhat-developer/app-services-sdk-java/blob/main/packages/kafka-management-sdk/README.md#maven-users

We should replace TBA with actual links to packages

**Comment by himanshu007-creator** [comment]
HI , i would like to work on this issue

**Comment by wtrocki** [comment]
@himanshu007-creator We do not assign issues. Feel free to create PR - that is equivalent to message that you are working on the issue
