### ISSUE TITLE
com.fasterxml.jackson.databind.exc.InvalidDefinitionException: Cannot construct instance of `org.openapitools.jackson.nullable.JsonNullable` (no Creators, like default construct, exist): cannot deserialize from Object value (no delegate- or property-based Creator)

### ISSUE THREAD

**Issue by k-wall** [redhat-developer/app-services-sdk-java#233]
Since 0.17 topic objects with leaders are failing to unmarshal, the exception we are seeing is:

```
com.fasterxml.jackson.databind.exc.InvalidDefinitionException: Cannot construct instance of `org.openapitools.jackson.nullable.JsonNullable` (no Creators, like default construct, exist): cannot deserialize from Object value (no delegate- or property-based Creator)
```

Here's a simple test that reproduces the issue.  The problem appears to be with the setter.

https://github.com/k-wall/app-services-sdk-java/blob/unmarshal-topic-exception/examples/src/integration-test/java/com/redhat/cloud/UnmarhsalTopicTest.java

**Comment by wtrocki** [comment]
@k-wall Thank you for logging issue. 0.17.0 introduced number of breaking changes and we are in process of testing it against unreleased service.

If problem occurs with production version I recommend downgrading to 0.16.0 for now.

**Comment by wtrocki** [comment]
Sorry for inconvenience
