### ISSUE TITLE
Provide examples for each SDK that are part of the compilation/PR build

### ISSUE THREAD

**Issue by wtrocki** [redhat-developer/app-services-sdk-java#30]
Examples can show code how things are used and we can use them to verify if generation works. 

See also: 
https://github.com/redhat-developer/app-services-sdk-go/issues/128

**Comment by secondsun** [comment]
First PR here : https://github.com/redhat-developer/app-services-sdk-java/pull/87

This adds a tests package that includes code samples which verify code generation worked. (Currently only one example is included)
