### ISSUE TITLE
API validation works only for golang SDK

### ISSUE THREAD

**Issue by wtrocki** [redhat-developer/app-services-sdk-java#70]
Golang SDK has validation for api standards that needs to be moved.

**Comment by wtrocki** [comment]
See https://github.com/redhat-developer/app-services-sdk-js/issues/139

**Comment by craicoverflow** [comment]
> 2021/08/05 15:36:02 encountered disallowed external reference: "kas-fleet-manager.yaml#/components/schemas/Error"

This comes from a separate library which does not support external references. The error happens here: https://github.com/redhat-developer/app-services-sdk-go/blob/d3ef7c96e96df7031f48dd706bbe3e9b92e3b4a8/internal/apigen/generator/golang/generate.go#L62

See https://github.com/deepmap/oapi-codegen/issues/42

So there is nothing to worry about here, there is no missing validation.
